---

- include_role:
    name: minishift
  when: run_minishift_role

- include_tasks: set_appropriate_oc_path.yml
  when: oc_path is not defined

- include_tasks: install_distro.yml
- include_tasks: log_admin.yml
- include_tasks: set_istio_distro_dir.yml
- include_tasks: create_namespace.yml
- include_tasks: change_scc.yml
- include_tasks: install_on_ocp.yml

- name: Install bookinfo showcase
  include_tasks: install_bookinfo.yml
  when: istio.bookinfo


- name: Open browser
  include_tasks: open_apps.yml
  when: istio.open_apps