- name: Choose command that opens URLs
  set_fact:
    browser_open_cmd: "{{'xdg-open' if ansible_distribution == 'Ubuntu' else 'open'}}"

- name: Get Route and open web screens
  shell: |
    SERVICEGRAPH=$({{ oc_path }} get route servicegraph -o jsonpath='{.spec.host}{"\n"}')
    GRAFANA=$({{ oc_path }} get route grafana -o jsonpath='{.spec.host}{"\n"}')
    PRODUCTPAGE=$({{ oc_path }} get route productpage -o jsonpath='{.spec.host}{"\n"}')
    ZIPKIN=$({{ oc_path }} get route zipkin -o jsonpath='{.spec.host}{"\n"}')

    {{browser_open_cmd}} http://$SERVICEGRAPH/dotviz
    {{browser_open_cmd}} http://$GRAFANA/dashboard/db/istio-dashboard
    {{browser_open_cmd}} http://$ZIPKIN/zipkin/
    {{browser_open_cmd}} http://$PRODUCTPAGE/productpage

- name: Get Jaeger Route
  shell: |
   {{browser_open_cmd}} http://$ZIPKIN/zipkin/
  when: istio.jaeger