- name: Define SCC rules
  shell: |
    oc adm policy add-scc-to-user anyuid -z istio-ingress-service-account
    oc adm policy add-scc-to-user anyuid -z istio-egress-service-account
    oc adm policy add-scc-to-user anyuid -z istio-pilot-service-account
    oc adm policy add-scc-to-user anyuid -z istio-mixer-service-account
    oc adm policy add-scc-to-user anyuid -z istio-ca-service-account
    oc adm policy add-scc-to-user anyuid -z default

    oc adm policy add-scc-to-user privileged -z default -z istio-system