- name: Set release tag to latest
  set_fact:
    release_tag: 'latest'
  when: istio.release_tag_name == ''

- name: Set release tag to specific versioned
  set_fact:
    release_tag: "tags/{{ istio.release_tag_name }}"
  when: istio.release_tag_name != ''

- name: Get the tagged release
  uri:
    url: "{{ istio.github_url }}/{{ istio.repo }}/releases/{{ release_tag }}"
  register: release

- name: Set release
  set_fact:
    assets_url: "{{ release.json.assets_url }}"

- name: Should have an assets_url
  assert:
    that: assets_url is defined

# - name: debug
#   debug:
#     var: assets_url

- name: Get the list of assets
  uri:
    url: "{{ assets_url }}"
  register: assets

- name: Set file extension to lookup
  set_fact:
    ext_pattern: "{{'.*osx.*' if ansible_os_family == 'Darwin' else '.*linux.*'}}"

- name: Extract the matching download url
  set_fact:
    asset_url: "{{assets.json | map(attribute='browser_download_url') | select('match', ext_pattern) | first}}"

- name: Extract the name of the asset
  set_fact:
    asset_name: "{{ asset_url | basename }}"