- name: Check if Istio distro folder exists
  stat:
    path: "{{ istio.dest }}/istio-{{ istio.release_tag_name }}"
  register: p

- debug: var=p.stat.path

- name: Install Istio distribution
  include_tasks: install.yml
  when: not p.stat.exists

- name: Add istio bin dir to PATH
  import_tasks: add_to_path.yml