---

- include_tasks: check_state.yml

- debug:
    msg: "Shutting down minishift..."
  when: minishift_is_running

- name: Shutdown minishift
  command: minishift stop --profile {{ minishift.profile.name }}
  when: minishift_is_running
  ignore_errors: yes

# ISSUE : The minishift vm is not deleted if you don't specify the user home env
# https://github.com/minishift/minishift/issues/1717
- name: Deleting minishift VM under profile {{ minishift.profile.name }}
  command: minishift delete --profile {{ minishift.profile.name }} --force
  become: yes
  ignore_errors: true
  environment:
    MINISHIFT_HOME: "{{ ansible_env.HOME }}/.minishift"
