---

- name: Check if minishift has been installed
  command: minishift version
  ignore_errors: yes
  register: ms

- name: Install minishift if it does not exist
  include_role:
    name: chouseknecht.minishift-up-role
  when: ms.failed

- include_tasks: delete.yml
  when: minishift.delete_existing

- include_tasks: check_state.yml

- name: Minishift status
  debug:
    msg: "Minishift is already started ..."
  when: minishift_is_running

- include_tasks: start.yml
  when: not minishift_is_running

- include_tasks: check_state.yml

- name: Ensure minishift is running
  assert:
    that: minishift_is_running
    msg: "Something went wrong while starting minishift... Checkout the 'minishift start' logs at {{start_output}}"

- include_tasks: set_cmd_path.yml