---
#Some of this code can be found in chouseknecht/minishift-up-role/copy_oc_client.yml

- name: Lookup path to the oc versions installed by minishift
  find:
    paths: "{{ lookup('env', 'HOME') }}/.minishift/cache/oc"
    patterns: "v*"
    hidden: yes
    file_type: directory
  register: oc_versions

#- debug:
#    var: oc_versions.files

- name: Set latest_oc_version
  set_fact:
    latest_oc_version: "{{ oc_versions.files | last }}"

- name: Lookup path to the oc binaries for the specified version
  find:
    paths: "{{ latest_oc_version.path }}"
    patterns: "oc"
    recurse: yes
    hidden: yes
    file_type: file
  register: matching_oc_files

#- debug:
#    var: matching_oc_files.files

- name: Use first matching oc file
  set_fact:
    first_matching_oc_file: "{{ matching_oc_files.files | first }}"

- name: Set oc_path from discovered binaries
  set_fact:
    oc_path: "{{ first_matching_oc_file.path }}"