- name: Load config of the minishift vm
  include_vars: vm_config.yaml

- name: Configure minishift vm, cpu, memory
  shell: |
    minishift config set {{ item.key }} {{ item.value }}
  with_items: "{{ parameters }}"

- name: Add minishift addon
  command: minishift addon enable admin-user