- name: Check if minishift is running
  command: minishift status --profile {{ profile.name }}
  register: ps_state
  ignore_errors: yes

- debug:
    msg: "Shutting down minishift..."
  when: '"Running" in ps_state.stdout'

- name: Shutdown minishift
  command: minishift stop --profile {{ profile.name }}
  when: '"Running" in ps_state.stdout'
  ignore_errors: yes

# ISSUE : The minishift vm is not deleted if you don't specify the user home env
# https://github.com/minishift/minishift/issues/1717
- name: Deleting minishift
  shell: |
    MINISHIFT_HOME={{ ansible_env.HOME }}/.minishift minishift delete --profile {{ profile.name }} --force
  become: yes
  ignore_errors: true
