- name: Check if minishift is running
  command: minishift status --profile {{ profile.name }}
  register: ps_state
  ignore_errors: yes

- set_fact: is_running={{ ps_state.stdout is defined and "Running" in ps_state.stdout }}

- debug:
    msg: "Shutting down minishift..."
  when: is_running

- name: Shutdown minishift
  command: minishift stop --profile {{ profile.name }}
  when: is_running
  ignore_errors: yes

# ISSUE : The minishift vm is not deleted if you don't specify the user home env
# https://github.com/minishift/minishift/issues/1717
- name: Deleting minishift
  command: minishift delete --profile {{ profile.name }} --force
  become: yes
  ignore_errors: true
  environment:
    MINISHIFT_HOME: "{{ ansible_env.HOME }}/.minishift"
