- name: Check if minishift is running
  command: minishift status --profile {{ profile.name }}
  register: ps_state
  ignore_errors: yes

- name: Minishift status
  debug:
    msg: "Minishift is already started ..."
  when: '"Running" in ps_state.stdout'

- name: Start minishift
  shell: |
    minishift profile set {{ profile.name }}
    minishift start --profile {{ profile.name }} >/tmp/minishift.out 2>&1
  ignore_errors: yes
  when: '"Running" not in ps_state.stdout'