---
- hosts: localhost
  gather_facts: true
  vars_files:
    - etc/config.yaml

  tasks:
    - import_tasks: minishift/delete.yml
      when: action == 'delete-vm'

    - name: Create Minishift VM, namespace for istio and change security rules
      block:
      - import_tasks: minishift/config.yml
      - import_tasks: istio/create_namespace.yml
      - import_tasks: istio/change_scc.yml
      when: action == 'create-vm'

    # Default process if a Minishift VM has already been provisioned
    - import_tasks: minishift/start.yml
    - import_tasks: ocp/log_admin.yml

    # Install Istio Distro if it doesn't exist
    - import_tasks: istio/install_distro.yml
      when: action == 'install-distro'



