---
- hosts: localhost
  gather_facts: true
  vars:
    # ansible_python_interpreter: /usr/bin/python3

  vars_files:
    - etc/config.yaml

  tasks:
    - import_tasks: minishift_setup.yml
    - import_tasks: ocp_post.yml